### ISSUE TITLE
Improve discoverability on HF

### ISSUE THREAD

**Issue by NielsRogge** [facebookresearch/segment-anything-2#1]
Hi,

Niels here from the open-source team at Hugging Face. Congrats on your work!

It would be great to make the checkpoints available on HF, along with dedicated model cards, which also enhances the visibility of your work. People could find them when searching https://huggingface.co/models?pipeline_tag=mask-generation&sort=trending.

This also comes with download stats, so that you see how many times people download your models.

e.g. facebook/sam-vit-base has been downloaded 530k times last month: https://huggingface.co/facebook/sam-vit-base.

## 1. Upload checkpoints in seperate model repos

Ideally, each checkpoint is pushed to a separate model repository. Here's a guide for uploading models to the 🤗 hub: https://huggingface.co/docs/hub/models-uploading. For this use case, I assume that the [PyTorchModelHubMixin](https://huggingface.co/docs/hub/models-uploading#upload-a-pytorch-model-using-huggingfacehub) class is best suited, it creates a config.json along with safetensors for each model.

## 2. Make the model Transformers compatible

In case you want your models to be usable through the Transformers library with `trust_remote_code=True`, I highly recommend following this guide: https://huggingface.co/docs/transformers/custom_models. It basically allows people to use your backbones using the `AutoModel` and `AutoModelForMaskGeneration` APIs.

We recently did the same with the MambaVision author as can be seen here: https://huggingface.co/collections/nvidia/mambavision-66943871a6b36c9e78b327d3.

Let me know if you need any help regarding this!

Cheers,

Niels
ML Engineer @ HF 🤗

**Comment by giswqs** [comment]
When I saw the new release about SAM 2, my first reaction was going to HF to see if it is available there. Unortunately, not yet. Would be awesome to see SAM 2 compatible with the transformers package.

**Comment by kalyanvasudev** [comment]
Thanks for the input. HF integration with native transformers support will be added very soon.
