### ISSUE TITLE
Can release your training code?Thanks

### ISSUE THREAD

**Issue by songyang86** [facebookresearch/segment-anything-2#12]

**Comment by omranlm** [comment]
Let us know, it it goes with training/fine tuning code

**Comment by bhack** [comment]
Any feedback on this from the team?

**Comment by bhack** [comment]
A tutorial for the image only fine-tuning is available at
https://medium.com/@sagieppel/train-fine-tune-segment-anything-2-sam-2-in-60-lines-of-code-928dd29a63b3

**Comment by bhack** [comment]
In the meantime I have a question:
As in the paper table it seems that you have used a `batch_size: 256` on training is this cause you have used 256 A100? 
I suppose that if in the training you need to maintain the predictor state and handle the reset state you need to work with 1 batch/8 frames sample x GPU right?

**Comment by JunMa11** [comment]
Hi @songyang86 @omranlm 

Here is the fine-tuning code for image segmentation
https://github.com/bowang-lab/MedSAM/blob/MedSAM2/README.md

**Comment by haithamkhedr** [comment]
Thanks for you all for your interest. We released the training code and provide some examples to [get started](https://github.com/facebookresearch/segment-anything-2/tree/main/training#getting-started).
