### ISSUE TITLE
I want to install SAM 2 on M1 Macbook, but with CUDA error

### ISSUE THREAD

**Issue by sangwf** [facebookresearch/segment-anything-2#122]
Does that mean I can't do it right now?

Thanks.

**Comment by SimonZeng7108** [comment]
https://github.com/SauravMaheshkar/samv2

**Comment by ronghanghu** [comment]
Hi @sangwf, we have recently made the CUDA extension step optional (in https://github.com/facebookresearch/segment-anything-2/pull/155) as a workaround to this problem.

You can pull the latest code and reinstall via
```bash
# run the line below inside the SAM 2 repo
git pull;
pip uninstall -y SAM-2;
rm -f sam2/*.so;
pip install -e ".[demo]"
```
which allows using SAM 2 without CUDA extension (the results should stay the same in most cases, see [`INSTALL.md`](https://github.com/facebookresearch/segment-anything-2/blob/main/INSTALL.md) for details).

**Comment by albertjo** [comment]
@ronghanghu I tried following the steps specified in [INSTALL.md](https://github.com/facebookresearch/segment-anything-2/blob/main/INSTALL.md) for the latest code. 

```
# skip the SAM 2 CUDA extension
SAM2_BUILD_CUDA=0 pip install -e ".[demo]"
```

The installation is successful but when I call `build_sam2_video_predictor`, I'm getting an `AssertionError: Torch not compiled with CUDA enabled` error.

I'm following the steps in "video predictor example" notebook. What could I be doing wrong?

**Comment by ronghanghu** [comment]
@albertjo do you have a GPU in your machine and installed a CUDA version of PyTorch?

Currently the SAM 2 repo doesn't support CPU-only or other devices yet (we might provide this support later). At this moment, if you don't have a GPU on your machine, you may use a few community adaptation in https://github.com/facebookresearch/segment-anything-2/issues/71#issuecomment-2261295494 or https://github.com/facebookresearch/segment-anything-2/pull/123

**Comment by ronghanghu** [comment]
Hi @sangwf @albertjo we have recently updated the notebooks to include M1 Chip and MPS examples in https://github.com/facebookresearch/segment-anything-2/pull/192. Please pull the latest code from this repo and try them out. Thanks!
