### ISSUE TITLE
CUDA_PATH error despite having it set up

### ISSUE THREAD

**Issue by 25benjaminli** [facebookresearch/segment-anything-2#133]
Hello, I am trying to install dependencies for the repository but keep getting this error:
`OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.`

Running `print(os.environ.get('CUDA_PATH'))`  yields a path to my current CUDA installation (v12.3)
The following code does as well:
`import torch; from torch.utils.cpp_extension import CUDA_HOME; print(torch.cuda.is_available(), CUDA_HOME)`

Not sure if this is a windows-specific issue or something, but CUDA_HOME is definitely in my environment variables.

**Comment by AmmoniumX** [comment]
I am having the exact same issue, both CUDA_HOME and CUDA_PATH are set, and torch is able to detect cuda, but installing SAM2 fails with said OSError.

```
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(venv) PS C:\Users\user\OneDrive\Documents\segment-anything-2> echo $Env:CUDA_HOME
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4
(venv) PS C:\Users\user\OneDrive\Documents\segment-anything-2> echo $Env:CUDA_PATH
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4
```

**Comment by AmmoniumX** [comment]
Running `pip install --no-build-isolation -e .` as was recommended in https://github.com/facebookresearch/segment-anything-2/issues/19 fixed my issue

**Comment by 25benjaminli** [comment]
@AmmoniumX Thank you for the recommendation, the steps detailed in #19 fixed my issue!
