### ISSUE TITLE
ERROR: Could not build wheels for SAM-2, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by hank1101444** [facebookresearch/segment-anything-2#142]
Hello,

I encountered an issue while attempting to install a package using the command `pip install -e .`. The error message indicates a CUDA version mismatch, stating that the expected version is 11.5. However, I have confirmed that my system is running CUDA version 12.1.

**Python and CUDA Version:**
```python
import torch
print(torch.__version__)
# Output: 2.4.0+cu121
```

**Steps to Reproduce:**
1. Run `pip install -e .` in the terminal.

**Actual Behavior:**
The installation fails with the following error message:
```
raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
RuntimeError:
The detected CUDA version (11.5) mismatches the version that was used to compile
PyTorch (12.1). Please make sure to use the same CUDA versions.

[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building editable for SAM-2
Failed to build SAM-2
ERROR: Could not build wheels for SAM-2, which is required to install pyproject.toml-based projects
```

**Question:**
Why is the system detecting my CUDA version as 11.5 when `torch.__version__` shows 2.4.0+cu121, which suggests it should be 12.1?

Could you please help me resolve this issue or guide me on how to bypass this version check?

Thank you!

---

**Comment by bluesaiyancodes** [comment]
I was also having similar issue. Can you check whats your CUDA_EXPORT ?
I pointed it to  `/usr/local/cuda-12.6/`, which mitigated the issue.

**Comment by ronghanghu** [comment]
Hi @hank1101444, the compilation step checks the version of your CUDA toolkit (instead of the version your PyTorch installation is linked to). Could you try running `nvcc --version` and see what version it shows up? If you have CUDA 12.1 toolkit correct installed and set up in your env, it should show up as follows:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
```

If you have a CUDA 12.1 toolkits installed locally (which would typically be in `/usr/local/cuda-12.1`), you can try the following
```
export CUDA_HOME=/usr/local/cuda-12.1
```
before the installation. If the CUDA 12.1 toolkits are not installed yet, you can install them from https://developer.nvidia.com/cuda-toolkit-archive

**Comment by ronghanghu** [comment]
Follow-up: We have recently made the CUDA extension step optional (in https://github.com/facebookresearch/segment-anything-2/pull/155) as a workaround to this problem.

You can pull the latest code and reinstall via
```bash
# run the line below inside the SAM 2 repo
git pull;
pip uninstall -y SAM-2;
rm -f sam2/*.so;
pip install -e ".[demo]"
```
which allows using SAM 2 without CUDA extension (the results should stay the same in most cases, see [`INSTALL.md`](https://github.com/facebookresearch/segment-anything-2/blob/main/INSTALL.md) for details).
