### ISSUE TITLE
FPS in Table 7 in not fair

### ISSUE THREAD

**Issue by qinliuliuqin** [facebookresearch/segment-anything-2#15]
Thanks for the interesting work. In Table 7, the FPS of existing methods were taken from Cutie. This is strange because you already ran these methods on your machines to obtain SA-V results. Why didn't you just report the FPS numbers you got in your machines for fair comparisons?

**Comment by feichtenhofer** [comment]
Even if run on exactly the same machines, there is no direct comparison because of different setups, environments, and other caveats such as data loading and implementation details. We've removed the speed comparison in Table 7 from the paper.
