### ISSUE TITLE
Inference with SAM 2 feels real-time at approximately 44 frames per second?

### ISSUE THREAD

**Issue by ArachisTong** [facebookresearch/segment-anything-2#159]
Referring to the video_predictor_ example. ipynb code, the A100 machine can only achieve a speed of 20.78it/s, but https://ai.meta.com/blog/segment-anything-2/ Mentioned in the middle“ inference with SAM 2 feels real-time at approximately 44 frames per second”How to reproduce optimal performance or provide evaluation scripts？

**Comment by ronghanghu** [comment]
Hi @ArachisTong, as mentioned in the [SAM 2 paper](https://arxiv.org/pdf/2408.00714) Sec 7
> SAM 2 based on Hiera-B+ and Hiera-L runs at real-time speeds of 43.8 and 30.2 FPS, respectively.

Note that this speed is measured using `torch.compile` as mentioned in https://github.com/facebookresearch/segment-anything-2?tab=readme-ov-file#model-description
