### ISSUE TITLE
How sam2_configs pushed in the {sys.path} in python?

### ISSUE THREAD

**Issue by aza1200** [facebookresearch/segment-anything-2#160]
By the [segment-anything-2/INSTALL.md](https://github.com/facebookresearch/segment-anything-2/blob/0230c5ff9335347bef063a2d88b9ede907f1be01/INSTALL.md)'s comment

It says that 

----
<summary>
I got `MissingConfigException: Cannot find primary config 'sam2_hiera_l.yaml'`
</summary>
<br/>

This is usually because you haven't run the `pip install -e .` step above, so `sam2_configs` isn't in your Python's `sys.path`. Please run this installation step. In case it still fails after the installation step, you may try manually adding the root of this repo to `PYTHONPATH` via
```bash
export SAM2_REPO_ROOT=/path/to/segment-anything  # path to this repo
export PYTHONPATH="${SAM2_REPO_ROOT}:${PYTHONPATH}"
```
to manually add `sam2_configs` into your Python's `sys.path`.

----

But I can't find out
how sam2_configs are inserted by executing 
```
pip install -e .
```

I know that acting means python setup.py 
But in that file there is no indication that insert python.syspath

**Comment by ronghanghu** [comment]
Hi @aza1200, do you encounter any failures after `pip install -e .` (or manually adding the repo root to `PYTHONPATH`) as in https://github.com/facebookresearch/segment-anything-2/blob/main/INSTALL.md?

> I know that acting means python setup.py
> But in that file there is no indication that insert python.syspath

Regarding `pip install -e .`, it would usually create a link to the SAM 2 repo path (in my environment, it adds a link in my Anaconda environment at
`~/anaconda3/envs/base/lib/python3.10/site-packages/__editable__.SAM_2-1.0.pth`) to allow editable installations. See details in https://setuptools.pypa.io/en/latest/userguide/development_mode.html.

**Comment by FurkanGozukara** [comment]
i am giving direct path and not working i cant make sense of this

https://github.com/facebookresearch/sam2/issues/544
