### ISSUE TITLE
Using SAM 2 on Jetson Orin Nano Ubuntu 22.04

### ISSUE THREAD

**Issue by Shahriarch** [facebookresearch/segment-anything-2#161]
I have tried to install SAM 2 on Jetson Orin Nano with Ubuntu 22.04 and Cuda 12.2. But Got the same problem as CUDE_HOME variable. Tried to set the Variable and no-build-Isolation as well, but none f it worked. Would appreciate it if anyone tried this?

**Comment by ronghanghu** [comment]
Hi, we have recently made the CUDA extension step optional (in https://github.com/facebookresearch/segment-anything-2/pull/155) as a workaround to this problem.

You can pull the latest code and reinstall via
```bash
# run the line below inside the SAM 2 repo
git pull;
pip uninstall -y SAM-2;
rm -f sam2/*.so;
pip install -e ".[demo]"
```
which allows using SAM 2 without CUDA extension (the results should stay the same in most cases, see [`INSTALL.md`](https://github.com/facebookresearch/segment-anything-2/blob/main/INSTALL.md) for details).

**Comment by Shahriarch** [comment]
For future users, To install SAM2 without CUDA extension, the solution is to use:  
```
# skip the SAM 2 CUDA extension
SAM2_BUILD_CUDA=0 pip install -e ".[demo]"
```
as described in [https://github.com/facebookresearch/segment-anything-2/blob/main/INSTALL.md](url)

**Comment by Shahriarch** [comment]
thnx

**Comment by IMddubin** [comment]
I’m working with a Orin NX setup and was wondering if anyone could share the versions of Torch and Torchvision installed?

I tried to install torch 2.4.0a0+07cecf4168.nv24.5, torchvision 0.19.0
but sam2 doesn't work

**Comment by Shahriarch** [comment]
I tried the versions mentioned in installation guidance which is PyTorch ≥ 2.3.1.

**Comment by sufianetaouil** [comment]
For anyone using Jetson having issues with CUDA_HOME not set, I solved it by installing using --no-build-isolation option:

`pip install -e . --no-build-isolation`

You'll notice it'll download torch and torchvision, but without CUDA support, so wait until the installation is finished, then reinstall torch and torchvision using the build wheels provided by Nvidia.

**Comment by sufianetaouil** [comment]
@IMddubin For me I used torch 2.4 provided by Nvidia, but I couldn't build torchvision 0.19 nor it was provided, so I used 0.18.0, which seems to be working fine with SAM2 even though it does not meet the requirements and SAM2 does complain about it when installing.

**Comment by Shahriarch** [comment]
You are not able to build it in your m
