### ISSUE TITLE
Segmentation using multiple prompt points

### ISSUE THREAD

**Issue by YiftyD** [facebookresearch/segment-anything-2#168]
Hi,
I noticed that when I use several propt points as an input I get one mask which includes all the detected objects, unlike SAM where I used to get a mask for each detected object. Is it a matter of a certain initlialization which needs to be used or specific parameters that need to be used?

Thank you very much in advance

**Comment by haithamkhedr** [comment]
Hi @YiftyD, please check the [image_predictor_exmaple](https://github.com/facebookresearch/segment-anything-2/blob/main/notebooks/image_predictor_example.ipynb) notebook. There is an example usage with batched input points towards the end
