### ISSUE TITLE
Config path issue

### ISSUE THREAD

**Issue by shersoni610** [facebookresearch/segment-anything-2#177]
Hello, 

I installed SAM2 on my linux machine successfully. Now, I am trying to use in a different directory where I copied both the models and sam2_config file. When I tried running the code. I get the following errors. 
File "/media/csverma/M2Disk/Projects/CompVis/ImageSegmentation/SAM2/sam2env/lib/python3.12/site-packages/hydra/_internal/defaults_list.py", line 464, in _create_defaults_tree_impl
    config_not_found_error(repo=repo, tree=root)
  File "/media/csverma/M2Disk/Projects/CompVis/ImageSegmentation/SAM2/sam2env/lib/python3.12/site-packages/hydra/_internal/defaults_list.py", line 799, in config_not_found_error
    raise MissingConfigException(
hydra.errors.MissingConfigException: Cannot find primary config './sam2_configs/sam2_hiera_l.yaml'. Check that it's in your config search path.

Config search path:
	provider=hydra, path=pkg://hydra.conf
	provider=main, path=pkg://sam2_configs
	provider=schema, path=structured://

I tried giving both the relative and absolute paths to the config file but it did not help. What mistake I may be doing?

Thanks

**Comment by ronghanghu** [comment]
Hi @shersoni610, I guess it's likely because you installed SAM 2 without the `-e` option in `pip install`, so it didn't copy over the config files during installation. This issue should be resolved after https://github.com/facebookresearch/segment-anything-2/pull/176.

For now, you can use the `ronghanghu/colab` branch in https://github.com/ronghanghu/segment-anything-2 as a workaround
```
pip install 'git+https://github.com/ronghanghu/segment-anything-2.git@ronghanghu/colab'
```

**Comment by ronghanghu** [comment]
Update: the changes above have been merged.

You can try reinstalling SAM 2 as follows
```
pip uninstall -y SAM-2; pip install 'git+https://github.com/facebookresearch/segment-anything-2.git'
```

**Comment by omry** [comment]
This looks like the same underlying issue tracked in #758.

`build_sam2()` currently passes its `config_file` argument directly to Hydra as `compose(config_name=...)`. In Hydra, `config_name` is resolved from the configured search path; it is not an arbitrary absolute filesystem path.

I added more context and a user-side workaround here:

https://github.com/facebookresearch/sam2/issues/758#issuecomment-4764826366

The workaround keeps the two concepts separate:

- `config_dir`: where Hydra should search for configs
- `config_name`: the config name resolved inside that directory

That also allows the user config directory to contain additional subconfigs referenced from the user config's defaults list.
