### ISSUE TITLE
Slow Progress in "video_predictor_example.ipynb" for Longer Videos

### ISSUE THREAD

**Issue by kimu1018** [facebookresearch/segment-anything-2#180]
Hello,

I have been working with the "video_predictor_example.ipynb", specifically on "Example 1: Segment & track one object," and I'm encountering an issue related to the progress of the propagation step across different video lengths.

Here is the script from step 3:
`# run propagation throughout the video and collect the results in a dict
video_segments = {}  # video_segments contains the per-frame segmentation results
for out_frame_idx, out_obj_ids, out_mask_logits in predictor.propagate_in_video(inference_state):
    video_segments[out_frame_idx] = {
        out_obj_id: (out_mask_logits[i] > 0.0).cpu().numpy()
        for i, out_obj_id in enumerate(out_obj_ids)
    }`

When I used an 8-second video, the process took about 1 second per frame. However, with a 40-second video, it slowed down significantly to about 1 minute per frame. The processing time does not seem to scale linearly with video length.

Are there any known issues or potential optimizations that could help speed up the inference on longer videos? Any advice or insights would be greatly appreciated.

Thank you!

**Comment by kimu1018** [comment]
My GPU is RTX2070.

**Comment by heyoeyo** [comment]
That sounds like it may be a memory issue, though it's hard to say for sure. Does it slow down immediately (like it's 1 minute/frame on the first frame?) or after processing some number of frames?

In any case, there are [options to reduce VRAM usage](https://github.com/facebookresearch/segment-anything-2/blob/d421e0b040d2d5455086575b3a573009e3e4f879/sam2/sam2_video_predictor.py#L43-L45) on the `predictor.init_state` call that might be worth toggling on in case it is a memory issue.

**Comment by kimu1018** [comment]
Thank you for the detailed explanation.

I noticed that the decrease in processing speed occurred from the first frame. However, after setting "offload_video_to_cpu" to TRUE, the slowdown in processing speed was improved. This adjustment has been very beneficial.

Thank you for your assistance!
