### ISSUE TITLE
conda environment

### ISSUE THREAD

**Issue by faroit** [facebookresearch/segment-anything-2#181]
installation instructions as outlined in https://github.com/facebookresearch/segment-anything-2/blob/main/INSTALL.md are quite fragile, besides containerizing, has anyone managed to create a working conda environment that install the necessary cuda toolkit and compilers so that the pip installation can succeed?

if yes, could we add that environment as a contribution here?

**Comment by ronghanghu** [comment]
Hi, we have recently made the CUDA extension step optional (in https://github.com/facebookresearch/segment-anything-2/pull/155 and https://github.com/facebookresearch/segment-anything-2/pull/175), which should simplify the installation step and require only PyTorch, opencv, and a few other common dependencies.

You can pull the latest code and reinstall via
```bash
# run the line below inside the SAM 2 repo
git pull;
pip uninstall -y SAM-2;
rm -f sam2/*.so;
pip install -e ".[demo]"
```
which allows using SAM 2 without CUDA extension (the results should stay the same in most cases, see [`INSTALL.md`](https://github.com/facebookresearch/segment-anything-2/blob/main/INSTALL.md) for details).

**Comment by faroit** [comment]
@ronghanghu Thanks a lot for the update. Things work fine now, indeed.
