### ISSUE TITLE
export memory_attention module to onnx failed with RuntimeError: ScalarType ComplexFloat is an unexpected tensor scalar type.

### ISSUE THREAD

**Issue by Aimol-l** [facebookresearch/segment-anything-2#186]
I am trying to export various model modules of sam2 to onnx for use on c++, but I encountered an error exporting the memory_attention module and I couldn't find any solution.
I tried torch.onnx.export and torch.onnx.dynamo_export, but they failed.
This is the project address: https://github.com/Aimol-l/SAM2Export.git
View export_onnx.py
Thank you！！！

local env：
os: Arch linux x86
cuda: 12.5
***********************
addict                   2.4.0
antlr4-python3-runtime   4.9.3
certifi                  2024.7.4
charset-normalizer       3.3.2
coloredlogs              15.0.1
contourpy                1.2.1
cycler                   0.12.1
defusedxml               0.7.1
filelock                 3.15.4
flatbuffers              24.3.25
fonttools                4.53.1
fsspec                   2024.6.1
huggingface-hub          0.24.5
humanfriendly            10.0
hydra-core               1.3.2
idna                     3.7
importlib_metadata       8.2.0
iopath                   0.1.10
Jinja2                   3.1.4
jstyleson                0.0.2
kiwisolver               1.4.5
markdown-it-py           3.0.0
MarkupSafe               2.1.5
matplotlib               3.9.0
mdurl                    0.1.2
ml-dtypes                0.4.0
mpmath                   1.3.0
networkx                 3.1
numpy                    1.26.4
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        9.1.0.70
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.20.5
nvidia-nvjitlink-cu12    12.6.20
nvidia-nvtx-cu12         12.1.105
omegaconf                2.3.0
onnx                     1.16.2
onnx-simplifier          0.4.36
onnxruntime              1.16.3
onnxscript               0.1.0.dev20240808
onnxsim                  0.4.36
opencv-python            4.7.0.72
openvino                 2023.1.0.dev20230811
openvino-dev             2023.1.0.dev20230811
openvino-telemetry       2024.1.0
packaging                24.1
pillow                   10.4.0
pip                      24.0
platformdirs             4.2.2
portalocker              2.10.1
protobuf                 5.27.3
pycocotools              2.0.8
Pygments                 2.18.0
pyparsing                3.1.2
python-dateutil          2.9.0.post0
PyYAML                   6.0.1
regex                    2024.7.24
requests                 2.32.3
rich                     13.7.1
safetensors              0.4.3
SAM-2                    1.0
samexporter              0.4.1                /home/aimol/Documents/Python/samexporter
scipy                    1.10.1
segment-anything         1.0
setuptools               69.5.1
six                      1.16.0
supervision              0.6.0
sympy                    1.13.1
texttable                1.7.0
timm                     0.9.2
tokenizers               0.19.1
tomli                    2.0.1
torch                    2.4.0
torchvision              0.19.0
tqdm                     4.66.5
transformers             4.43.4
triton                   3.0.0
typing_extensions        4.12.2
urllib3                  2.2.2
wheel                    0.43.0
yapf                     0.40.2
zipp                     3.19.2

**Comment by bhack** [comment]
Have you tried with https://pytorch.org/docs/stable/onnx_dynamo.html and a fresh pytorch version?

**Comment by Aimol-l** [comment]
> Have you tried with https://pytorch.org/docs/stable/onnx_dynamo.html and a fresh pytorch version?

yep,I haven tried it. I have read this issue pytorch/pytorch # 59246, but it has not been resolved. Very confused :-)

**Comment by bhack** [comment]
But I suppose that in this case it is more:
https://github.com/pytorch/pytorch/issues/49793

**Comment by kyakuno** [comment]
We are also trying to export memory_attention to ONNX, but we are encountering the same error. Export results in a ComplexFloat error and onnx.dynamo_export results in an unknown error. We were able to export image_encoder, mask_decoder, prompt_encoder, and memory_encoder without any issues.

Code

```
            torch.onnx.export( # also dynamo_export
                self.memory_attention, (current_vision_feats[0], memory, current_vision_pos_embeds[0], memory_pos_embed, num_obj_ptr_tokens), 'memory_attention_'+model_id+'.onnx',
                input_names=["curr", "memory", "curr_pos", "memory_pos", "num_obj_ptr_tokens"],
                output_names=["pix_feat"],
                verbose=False, opset_version=17
            )
```
https://github.com/axinc-ai/segment-anything-2/blob/onnx/sam2/modeling/sam2_base.py#L709

Output

```
ScalarType ComplexFloat is an unexpected tensor scalar type
```

**Comment by bhack** [comment]
I suppose it is caused by 
https://github.com/facebookresearch/segment-anything-2/blob/main/sam2/modeling/position_encoding.py#L200

But it seems https://github.com/pytorch/pytorch/issues/49793 is closed or not?

**Comment by bhack** [comment]
What is the error with `onnx.dynamo_export`? What pytorch version?

**Comment by heyoeyo** [comment]
As far as I can tell, complex numbers are only being used to handle 2D rotations. So if compatibility is an issue, it's possible to convert the code over to use matrix multiplications instead.

It should be a matter of just changing how the complex numbers are computed (the [compute_axial_cis](https://github.com/facebookresearch/segment-anything-2/blob/7e1596c0b6462eb1d1ba7e1492430fed95023598/sam2/modeling/position_encoding.py#L174) function) to something that creates 2x2 matrices:
```python
def get_rotation_matrices(dim, end_x, end_y, theta=10000.0, device=None, dtype=None):
    
    powers = torch.linspace(0, 1, 1 + (dim // 4), device=device, dtype=dtype)[:-1]
    base_angles = torch.pow(theta, -powers)

    end_x, end_y = int(end_x), int(end_y)
    x_mults = torch.arange(end_x, device=device, dtype=dtype).repeat(end_y)
    y_mults = torch.arange(end_y, device=device, dtype=dtype).repeat_interleave(end_x)
    angles_xy = (torch.outer(mults, base_angles) for mults in (x_mults, y_mults))
    
    rotmats_list = []
    for angles in angles_xy:
        sterm, cterm = torch.sin(-angles), torch.cos(-angles)
        rotmat = torch.stack(
            [
                torch.stack([cterm, -sterm], dim=-1),
                torch.stack([sterm, cterm], dim=-1),
            ],
            dim=-1,
        )
        rotmats_list.append(rotmat)

    return torch.cat(rotmats_list, dim=1).unsqueeze(0).unsqueeze(0)
```

And then similarly changing over how the complex numbers are used to rotate tokens (the [apply_rotary_enc](https://github.com/facebookresearch/segment-anything-2/blob/7e1596c0b6462eb1d1ba7e1492430fed95023598/sam2/modeling/position_encoding.py#L194) function) to instead use the rotation matrices:
```python
def apply_rotary_enc(xq, xk, rotmats, repeat_freqs_k=False):
    
    bq, hq, nq, cq = xq.shape
    bk, hk, nk, ck = xk.shape

    q_out = torch.matmul(rotmats, xq.reshape(bq, hq, nq, cq // 2, 2, 1)).flatten(3)
    k_rotmat = rotmats.repeat(1, 1, nk // nq, 1, 1, 1) if repeat_freqs_k else rotmats
    k_out = torch.matmul(k_rotmat, xk.reshape(bk, hk, nk, ck // 2, 2, 1)).flatten(3)

    return q_out, k_out
```

This is pulled from a modified implementation, so there might be some other small tweaks needed for everything to run properly. However, from what I've seen, the complex number version runs extremely fast compared to using matrix multiplications. It seems there might be some special optimizations for complex numbers (maybe it doesn't matter in onnx though?).

**Comment by bhack** [comment]
Is the Rotary in torchtune compatible?
https://github.com/pytorch/torchtune/blob/main/torchtune/modules/position_embeddings.py#L14

**Comment by heyoeyo** [comment]
> Is the Rotary in torchtune compatible?

I'm not familiar with torchtune, but as far as I can tell, it looks like a 1D version of RoPE. It's also using a matrix multiplication (manually), so if it's converted to 2D, it should work.

**Comment by bhack** [comment]
@heyoeyo In any case `onnx.dynamo_export` it is working with complex but you need to use the API correctly. See the signature at https://pytorch.org/docs/stable/onnx_dynamo.html#id6

It seems that the real problem with onnx dynamo is:
```
AssertionError: Mutating module attribute freqs_cis during export.
```

**Comment by bhack** [comment]
See more at https://github.com/pytorch/pytorch/issues/106217

**Comment by heyoeyo** [comment]
> then the main problem is unsqueeze with complex

If `.reshape()` still works with complex numbers, then it should be possible to replace the `.unsqueeze()` with a reshape operation that just puts a 1 in whatever dimension the unsqueeze was adding. Or otherwise maybe the simpler `[None]` trick would work if even reshape isn't supported (i.e. these are equivalent: `data.unsqueeze(1) <-> data[:, None]`)

**Comment by bhack** [comment]
It seems to be more about the else case:
https://github.com/facebookresearch/segment-anything-2/blob/7e1596c0b6462eb1d1ba7e1492430fed95023598/sam2/modeling/position_encoding.py#L214-L219

I don't know on what device it is not working repeat on complex. Have you tried on CPU the repeat branch?

**Comment by bhack** [comment]
@ronghanghu Has done this commit. Can you expand a bit about the `repeat` on complex incompatibilites on non cuda devices?
As at the same time `unsqueeze` is not compatible with complex on onnx/export https://github.com/pytorch/pytorch/issues/106217

**Comment by bhack** [comment]
Asyou are working on different repositories/branches can you focus to open a DRAFT PR on this repo using `onnx.dynamo_export`?

I think It will be easier to track the progress/workarounds and get support form the original Meta team.

**Comment by kyakuno** [comment]
@heyoeyo Thank you for the information about replacing RotteryEncoder's Complex Tensor with Matmul. Using the provided code, I was able to convert it to ONNX with torch.export.
https://github.com/axinc-ai/segment-anything-2/blob/onnx/sam2/modeling/sam/transformer.py#L340
https://github.com/axinc-ai/segment-anything-2/blob/onnx/sam2/modeling/position_encoding.py#L224

Memory Attention Tiny : https://storage.googleapis.com/ailia-models/segment-anything-2/memory_attention_hiera_t.onnx
Netron : https://netron.app/?url=https://storage.googleapis.com/ailia-models/segment-anything-2/memory_attention_hiera_t.onnx

**Comment by MonolithFoundation** [comment]
@janghyuncho @kyakuno  Can u share your inference code?

thanks very much!

**Comment by Aimol-l** [comment]
> @janghyuncho @kyakuno Can u share your inference code?
> 
> thanks very much!

https://github.com/Aimol-l/OrtInference

**Comment by kyakuno** [comment]
@MonolithFoundation Our inference code is below. It also supports MemoryAttention.
https://github.com/axinc-ai/ailia-models/tree/master/image_segmentation/segment-anything-2

Use ONNX Runtime (121,714 ms for hiera_l on M2 Mac)

```
python3 segment-anything-2.py -v demo --onnx
```

Use our ailia SDK (24,106 ms for hiera_l on M2 Mac)

```
pip3 install ailia
python3 segment-anything-2.py -v demo
```

ONNX files are automatically downloaded.

**Comment by dxlcnm** [comment]
I only modify implementation of function `apply_rotary_enc` to `apply_rotary_enc_mat`, and export the onnx successfully. Got the almost same result.
https://github.com/dxlcnm/segment-anything-2-real-time-onnx/blob/main/sam2/modeling/position_encoding.py

**Comment by zsz00** [comment]
More than twice as slow


> I only modify implementation of function `apply_rotary_enc` to `apply_rotary_enc_mat`, and export the onnx successfully. Got the almost same result. https://github.com/dxlcnm/segment-anything-2-real-time-onnx/blob/main/sam2/modeling/position_encoding.py
