### ISSUE TITLE
Installing Error: CUDA_HOME environment variable is not set

### ISSUE THREAD

**Issue by iskenderkahramanoglu** [facebookresearch/segment-anything-2#19]
Thank for SAM2!

Firstly, I couldn't run "git clone git@github.com:facebookresearch/segment-anything-2.git" command, this give permission denied.
So I used "git clone https://github.com/facebookresearch/segment-anything-2.git" command.

Then when I tried "pip install -e ." command, I take this error

```
Obtaining file:///C:/Users/Admin/Downloads/segment-anything-2
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      C:\Users\Admin\AppData\Local\Temp\pip-build-env-8wwvwoh9\overlay\Lib\site-packages\torch\_subclasses\functional_tensor.py:258: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
        cpu = _conversion_method_template(device=torch.device("cpu"))
      Traceback (most recent call last):
        File "C:\Users\Admin\Envs\sam_env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Admin\Envs\sam_env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Admin\Envs\sam_env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-8wwvwoh9\overlay\Lib\site-packages\setuptools\build_meta.py", line 458, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-8wwvwoh9\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-8wwvwoh9\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-8wwvwoh9\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 70, in <module>
        File "<string>", line 51, in get_extensions
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-8wwvwoh9\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 1076, in CUDAExtension
          library_dirs += library_paths(cuda=True)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-8wwvwoh9\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 1214, in library_paths
          paths.append(_join_cuda_home(lib_dir))
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-8wwvwoh9\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 2416, in _join_cuda_home
          raise OSError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

What can I do?

Nvidia drivers and Cuda is installed, when I run nvcc -V, it gives this output:

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:36:15_Pacific_Daylight_Time_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
```

**Comment by GMDowling** [comment]
Second this. Even after setting the Windows system variable "CUDA_HOME" to the appropriate cuda 12.1 directory (to match the torch 2.3.1 requirement), and setting an overwrite environment variable for "CUDA_HOME" in a conda environment, I get an identical error to OP.

environment deets:
```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Feb_27_16:28:36_Pacific_Standard_Time_2024
Cuda compilation tools, release 12.4, V12.4.99
Build cuda_12.4.r12.4/compiler.33961263_0

echo %CUDA_HOME%
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1

python -c "import torch; print(torch.__version__); print(torch.cuda.is_available())"
2.3.1+cu121
True

python -c "import setuptools; print(setuptools.__version__);"
61.0.0
```

error:
```
(sam2env) C:\Users\gabe\Downloads\segment-anything-2>pip install -e .
Obtaining file:///C:/Users/gabe/Downloads/segment-anything-2
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      C:\Users\gabe\AppData\Local\Temp\pip-build-env-35rk4nwc\overlay\Lib\site-packages\torch\_subclasses\functional_tensor.py:258: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
        cpu = _conversion_method_template(device=torch.device("cpu"))
      Traceback (most recent call last):
        File "C:\Users\gabe\anaconda3\envs\sam2env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\gabe\anaconda3\envs\sam2env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\gabe\anaconda3\envs\sam2env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "C:\Users\gabe\AppData\Local\Temp\pip-build-env-35rk4nwc\overlay\Lib\site-packages\setuptools\build_meta.py", line 458, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "C:\Users\gabe\AppData\Local\Temp\pip-build-env-35rk4nwc\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\gabe\AppData\Local\Temp\pip-build-env-35rk4nwc\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\Users\gabe\AppData\Local\Temp\pip-build-env-35rk4nwc\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 70, in <module>
        File "<string>", line 51, in get_extensions
        File "C:\Users\gabe\AppData\Local\Temp\pip-build-env-35rk4nwc\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 1076, in CUDAExtension
          library_dirs += library_paths(cuda=True)
        File "C:\Users\gabe\AppData\Local\Temp\pip-build-env-35rk4nwc\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 1214, in library_paths
          paths.append(_join_cuda_home(lib_dir))
        File "C:\Users\gabe\AppData\Local\Temp\pip-build-env-35rk4nwc\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 2416, in _join_cuda_home
          raise OSError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

(sam2env) C:\Users\gabe\Downloads\segment-anything-2>
```

**Comment by 0xIbra** [comment]
Try

```
pip install --no-build-isolation -e .
```

> of course don't forget to properly set `CUDA_HOME` env var.

**Comment by Li291216576** [comment]
thanks a lot, it works for me!

**Comment by GMDowling** [comment]
Works for me, thanks!

**Comment by hananbeer** [comment]
> Try
> 
> ```
> pip install --no-build-isolation -e .
> ```
> 
> And of course don't forget to properly set `CUDA_HOME` env var.

thanks it works for me too, but strangely it didn't work for installing ".[demo]" with and without `--no-build-isolation`.

**Comment by Atlas3DSS** [comment]
> Try
> 
> ```
> pip install --no-build-isolation -e .
> ```
> 
> And of course don't forget to properly set `CUDA_HOME` env var.

thank you very much - i couldn't get passed this last night - should have known to just come here and ask

**Comment by hakemz91** [comment]
Got mine working by first run (pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121) and then (pip install --no-build-isolation -e .). Thanks

**Comment by XinrunXu** [comment]
donot work for me.
ERROR: Could not build wheels for SAM-2, which is required to install pyproject.toml-based projects

> Try
> 
> ```
> pip install --no-build-isolation -e .
> ```
> 
> And of course don't forget to properly set `CUDA_HOME` env var.

**Comment by seekme-ai** [comment]
(segment) PS E:\code\segment\segment-anything-2> echo $env:CUDA_HOME                                         
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4
(segment) PS E:\code\segment\segment-anything-2> pip install --no-build-isolation -e .
仍然报错：OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

**Comment by Huster-Hq** [comment]
> pip install --no-build-isolation -e .

Works for me, thanks!

**Comment by Huster-Hq** [comment]
> --no-build-isolation

it work for installing ".[demo]" with **--no-build-isolation** for me.

**Comment by ronghanghu** [comment]
Hi, we have added [`INSTALL.md`](https://github.com/facebookresearch/segment-anything-2/blob/main/INSTALL.md) as an installation FAQ.

Regarding this error:

This usually happens because the installation step cannot find the CUDA toolkits (that contain the NVCC compiler) to build a custom CUDA kernel in SAM 2. Please install [CUDA toolkits](https://developer.nvidia.com/cuda-toolkit-archive) or the version that matches the CUDA version for your PyTorch installation. If the error persists after installing CUDA toolkits, you may explicitly specify `CUDA_HOME` via
```
export CUDA_HOME=/usr/local/cuda  # change to your CUDA toolkit path
```
and rerun the installation.

Also, you should make sure
```
python -c 'import torch; from torch.utils.cpp_extension import CUDA_HOME; print(torch.cuda.is_available(), CUDA_HOME)'
```
print `(True, a directory with cuda)` to verify that the CUDA toolkits are correctly set up.

**Comment by ayoubft** [comment]
And if you are working on HPC cluster do not forget to : 
```
module load cuda
```  
!

**Comment by lmst2** [comment]
> Hi, we have added [`INSTALL.md`](https://github.com/facebookresearch/segment-anything-2/blob/main/INSTALL.md) as an installation FAQ.
> 
> Regarding this error:
> 
> This usually happens because the installation step cannot find the CUDA toolkits (that contain the NVCC compiler) to build a custom CUDA kernel in SAM 2. Please install [CUDA toolkits](https://developer.nvidia.com/cuda-toolkit-archive) or the version that matches the CUDA version for your PyTorch installation. If the error persists after installing CUDA toolkits, you may explicitly specify `CUDA_HOME` via
> 
> ```
> export CUDA_HOME=/usr/local/cuda  # change to your CUDA toolkit path
> ```
> 
> and rerun the installation.
> 
> Also, you should make sure
> 
> ```
> python -c 'import torch; from torch.utils.cpp_extension import CUDA_HOME; print(torch.cuda.is_available(), CUDA_HOME)'
> ```
> 
> print `(True, a directory with cuda)` to verify that the CUDA toolkits are correctly set up.

I have the same problem, and running `pip install --no-build-isolation -e .` does not work for me and `python -c 'import torch; from torch.utils.cpp_extension import CUDA_HOME; print(torch.cuda.is_available(), CUDA_HOME)'` gives me False, None but I have the cuda installed already, nvcc --version prints out 12.1.

So I digged into torch.utils.cpp_extension, found out the "CUDA_HOME" variable is set in dinamically through this code `CUDA_HOME = _find_cuda_home() if torch.cuda._is_compiled() else None` I dont know how `torch.cuda._is_compiled()` worked, but I guess its will only set cuda home when you installed pytorch with gpu version. but what I see in the setup.py, it only requires torch >= 2.3.1, which i guess will only install the cpu version.(point out if I were wrong) causing the CUDA_HOME set to None no metter what.

Then I runs the command on pytorch's website `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121`  after doing this. `python -c 'import torch; from torch.utils.cpp_extension import CUDA_HOME; print(torch.cuda.is_available(), CUDA_HOME)'` gives me True and the path. but `pip install  -e .` still not working. digging through log I found out the setup.py downloaded a new torch wheel which is cpu only and shows that message again. then I runs `pip install --no-build-isolation -e .` and it finally worked, so I guess `--no-build-isolation` uses my installed torch instead and it worked. 

With that been said. its clearly some errors in setup.py. simply requires tourch by putting `"torch>=2.3.1"` in required_packages seems not enough. it needs detect cuda installation and get torch with cuda from pytorch's official index instead. I don't know it I understand it correct. But this is my solution and thought. Hope this gives you some clue about whats actually going on. And not just giving a solution that bypass the cuda extension installation. since the gpu accelection is quite important.

**Comment by KLL535** [comment]
There are hundreds of subfolders, where should I link for: 
set CUDA_HOME=?
C:\Users\AnY\miniconda3\pkgs\cuda-toolkit
C:\Users\AnY\miniconda3\pkgs\cuda-toolkit\nvcc
C:\Users\AnY\miniconda3\pkgs\cuda-toolkit\nvcc\bin
C:\Users\AnY\miniconda3\pkgs\cuda-toolkit\nvcc\nvvm\bin
This path not work!

(venv) C:\python2\qwen2>pip install --no-build-isolation -e .
Obtaining file:///C:/python2/qwen2
ERROR: file:///C:/python2/qwen2 does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

**Comment by BJXSX** [comment]
> > Hi, we have added [`INSTALL.md`](https://github.com/facebookresearch/segment-anything-2/blob/main/INSTALL.md) as an installation FAQ.
> > Regarding this error:
> > This usually happens because the installation step cannot find the CUDA toolkits (that contain the NVCC compiler) to build a custom CUDA kernel in SAM 2. Please install [CUDA toolkits](https://developer.nvidia.com/cuda-toolkit-archive) or the version that matches the CUDA version for your PyTorch installation. If the error persists after installing CUDA toolkits, you may explicitly specify `CUDA_HOME` via
> > ```
> > export CUDA_HOME=/usr/local/cuda  # change to your CUDA toolkit path
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and rerun the installation.
> > Also, you should make sure
> > ```
> > python -c 'import torch; from torch.utils.cpp_extension import CUDA_HOME; print(torch.cuda.is_available(), CUDA_HOME)'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > print `(True, a directory with cuda)` to verify that the CUDA toolkits are correctly set up.
> 
> I have the same problem, and running `pip install --no-build-isolation -e .` does not work for me and `python -c 'import torch; from torch.utils.cpp_extension import CUDA_HOME; print(torch.cuda.is_available(), CUDA_HOME)'` gives me False, None but I have the cuda installed already, nvcc --version prints out 12.1.
> 
> So I digged into torch.utils.cpp_extension, found out the "CUDA_HOME" variable is set in dinamically through this code `CUDA_HOME = _find_cuda_home() if torch.cuda._is_compiled() else None` I dont know how `torch.cuda._is_compiled()` worked, but I guess its will only set cuda home when you installed pytorch with gpu version. but what I see in the setup.py, it only requires torch >= 2.3.1, which i guess will only install the cpu version.(point out if I were wrong) causing the CUDA_HOME set to None no metter what.
> 
> Then I runs the command on pytorch's website `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121` after doing this. `python -c 'import torch; from torch.utils.cpp_extension import CUDA_HOME; print(torch.cuda.is_available(), CUDA_HOME)'` gives me True and the path. but `pip install -e .` still not working. digging through log I found out the setup.py downloaded a new torch wheel which is cpu only and shows that message again. then I runs `pip install --no-build-isolation -e .` and it finally worked, so I guess `--no-build-isolation` uses my installed torch instead and it worked.
> 
> With that been said. its clearly some errors in setup.py. simply requires tourch by putting `"torch>=2.3.1"` in required_packages seems not enough. it needs detect cuda installation and get torch with cuda from pytorch's official index instead. I don't know if I understand it correctly. But this is my solution and thought. Hope this gives you some clue about whats actually going on. And not just giving a solution that bypass the cuda extension installation. since the gpu accelection is quite important.

Hi, 
First I very much  appreciate your effort to deal with this issue. I have done the same thing as you, and I'm pretty sure you are right. I have something to supplement:
When we use pip to install this package, it will create a build isolation to bulid the wheel. In this environment, it will install a new torch according to pyproject.toml. When I tried to fix  to some specific versions in which CUDA_HOME can be set correctly, a new error was rasied
```
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-o7_zqw2w\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 382, in _check_cuda_version
          torch_cuda_version = packaging.version.parse(torch.version.cuda)
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-o7_zqw2w\overlay\Lib\site-packages\packaging\version.py", line 56, in parse
          return Version(version)
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-o7_zqw2w\overlay\Lib\site-packages\packaging\version.py", line 200, in __init__
          match = self._regex.search(version)
      TypeError: expected string or bytes-like object
```
It demonstrated that the pytorch in the build isolation is CPU version indeed, because the return value of torch.version.cuda is None, but I don't know how to install a GPU version of pytorch in build isolation.
By the way, I have encountered this problems several times before, I have been bothered by it for a long time because there is no good analysis of it as far as I know
