### ISSUE TITLE
error when running sam2_video_predictor.py

### ISSUE THREAD

**Issue by JJayaL** [facebookresearch/segment-anything-2#191]
UserWarning: Flash Attention is disabled as it requires a GPU with Ampere (8.0) CUDA capability.
  OLD_GPU, USE_FLASH_ATTN, MATH_KERNEL_ON = get_sdpa_settings()
  
  I am using CUDA 12.3 and I have a Nvidia Tesla P100 GPU

**Comment by ronghanghu** [comment]
Hi, this warning is expected -- Nvidia Tesla P100 GPU has only 6.0 CUDA capabilities (see https://developer.nvidia.com/cuda-gpus) and is too old for Flash Attention. You can ignore this warning if if the notebooks or other functionalities work for you.
