### ISSUE TITLE
Independent Components 

### ISSUE THREAD

**Issue by shersoni610** [facebookresearch/segment-anything-2#193]
Hello,

It seems many binary masks generated by SAM2 are topological disconnected. Is there a way to get separate components using SAM2 or we have to write our own processing function?

Thans

**Comment by ronghanghu** [comment]
Hi @shersoni610, if you need to further get independent components from the SAM 2 output masks, you can use either
1. the [`get_connected_components`](https://github.com/facebookresearch/segment-anything-2/blob/778e1127404547429b281d9c9394ddb3652b85a5/sam2/utils/misc.py#L47-L63) function, which directly works with GPU which requires building the SAM 2 CUDA extension (it's adapted from [`cc_torch`](https://github.com/zsef123/Connected_components_PyTorch))
2. external libraries like [`cv2.connectedComponentsWithStats`](https://pyimagesearch.com/2021/02/22/opencv-connected-component-labeling-and-analysis/) or [`scipy.ndimage.label`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.label.html) or [`skimage.measure.label`](https://scikit-image.org/docs/stable/api/skimage.measure.html#skimage.measure.label)
