### ISSUE TITLE
"Flash attention" error in a GPU enabled laptop with CUDA 12.1, Windows 11, Pytorch 2.4.0

### ISSUE THREAD

**Issue by sleeplessTLV** [facebookresearch/segment-anything-2#219]
Hi,
Installed and downloaded all, Python 3.12 and Pytorch 2.4.0+cu121 (Cuda 12.1) installed.
running the basic Jupyter notebook.
at the prediction task I get
"c:\Python312\segment-anything-2\sam2\modeling\backbones\hieradet.py:68: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:555.)
  x = F.scaled_dot_product_attention("
 Previously on the  
 "from sam2.sam2_image_predictor import SAM2ImagePredictor"
 stage I got just a warning 
  "c:\Python312\segment-anything-2\sam2\modeling\sam\transformer.py:23: UserWarning: Flash Attention is disabled as it requires a GPU with Ampere (8.0) CUDA capability.
  OLD_GPU, USE_FLASH_ATTN, MATH_KERNEL_ON = get_sdpa_settings()"
So can I bypass this with some setting NOT to use FLASH Attention? 
thanks

**Comment by sleeplessTLV** [comment]
my bad, I don't know how to delete this issue, but apparently my mistake

**Comment by Dashenboy** [comment]
how did you fix this issue?

**Comment by ronghanghu** [comment]
@Dashenboy This is mainly a warning suggesting that the GPU is not supporting Flash Attention, so it will fall back to other scaled dot-product kernels. It doesn't needs fixing and you can still use SAM 2 in this case.

more details: Flash Attention is generally faster but is only fully supported with GPUs that have CUDA capabilities >= 8.0. If you GPU has a lower CUDA capability (as can be check on https://developer.nvidia.com/cuda-gpus), this warning will be printed suggesting that Flash Attention is not available for you (but you can ignore it).

**Comment by skylning** [comment]
My GPU is rtx4090,and it have CUDA capabilities=8.9,i also get this error
