### ISSUE TITLE
_C.so: undefined symbol

### ISSUE THREAD

**Issue by leviome** [facebookresearch/segment-anything-2#22]
THANKS FOR SAM2

```
from sam2 import _C
ImportError: /data/levi/segment-anything-2/sam2/_C.so: undefined symbol: _ZN3c1015SmallVectorBaseIjE8grow_podEPKvmm
```

pls tell me how to solve it.

**Comment by sarsmlee** [comment]
same problem

**Comment by leviome** [comment]
> same problem my env： ub22.04 python3.11 pytorch2.3.1&pytorch2.4.0 cuda11.8&12.1 same problem

 I'm trying solutions in #14 to downgrade pytorch to 2.1.0.

**Comment by sarsmlee** [comment]
> > same problem my env： ub22.04 python3.11 pytorch2.3.1&pytorch2.4.0 cuda11.8&12.1 same problem
> 
> I'm trying solutions in #14 to downgrade pytorch to 2.1.0.

but in setup.py, the pytorch version must be >=2.3.1

**Comment by fangli333** [comment]
> > same problem my env： ub22.04 python3.11 pytorch2.3.1&pytorch2.4.0 cuda11.8&12.1 same problem
> 
> I'm trying solutions in #14 to downgrade pytorch to 2.1.0.

did you succeed? how did you do that? Thank you.

**Comment by ZlodeiBaal** [comment]
Same issue. Tried to downgrade to 2.1.0 - did not help

**Comment by gijskoning** [comment]
It was solved for me after running: `python setup.py build_ext --inplace`

**Comment by whcpumpkin** [comment]
> It was solved for me after running: `python setup.py build_ext --inplace`

Me too.  GPT-4 told me to run this command. It solved.

**Comment by leviome** [comment]
> > > same problem my env： ub22.04 python3.11 pytorch2.3.1&pytorch2.4.0 cuda11.8&12.1 same problem
> > 
> > 
> > I'm trying solutions in #14 to downgrade pytorch to 2.1.0.
> 
> did you succeed? how did you do that? Thank you.

Yep, it worked.

**Comment by leviome** [comment]
> It was solved for me after running: `python setup.py build_ext --inplace`

this seems like a nicer solution than downgrading pytorch.

**Comment by yoobin-jeong** [comment]
I still have the issue even after `python setup.py build_ext --inplace`
is there any other way?

**Comment by yoobin-jeong** [comment]
> I still have the issue even after `python setup.py build_ext --inplace` is there any other way?

`python setup.py clean --all` then `ython setup.py build_ext --inplace` works for me

**Comment by wRossw** [comment]
Worked for me too. For anyone using Colab ran the following


```
import os

# Change directory to your project folder
project_dir = 'your_path'
os.chdir(project_dir)

# Remove the build directory if it exists
!rm -rf build

# Build the extension
!python setup.py build_ext --inplace
```

**Comment by ArmandAlbert** [comment]
> It was solved for me after running: `python setup.py build_ext --inplace`

This works! I found that the install file setup.py needs this command, or some packages are not installed correctly. Thanks a lot!

**Comment by zwfcrazy** [comment]
In my case, the undefined symbol is _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

This is caused by C++ ABI compatibility issue.
Pytorch 2.5.1 was compiled with gcc 9 while in my environment sam2 was compiled with gcc 11.

I have to downgrade the gcc in my environment to 9 in order to solve this problem.
