### ISSUE TITLE
Open3d import

### ISSUE THREAD

**Issue by omarrayyann** [facebookresearch/segment-anything-2#231]
For some reason, once I import the module, code gets stuck when I later try to import open3d. Any ideas why that could be the case?

**Comment by ronghanghu** [comment]
Hi @omarrayyann, it could be possible that Open3D has a few conflicts with PyTorch (https://github.com/isl-org/Open3D/issues/5597). You may try the solutions in this link and see if it resolves your problem.

Closing this issue since this conflict is beyond SAM 2 codebase.
