### ISSUE TITLE
coral edge tpu interface

### ISSUE THREAD

**Issue by MuhammadTayab** [facebookresearch/segment-anything-2#232]
I was curious if there is a version of SAM2 that is compatible with google coral tpu ?
Doesn't seem to find anything online for this.

**Comment by MR-HYS** [comment]
![image](https://github.com/user-attachments/assets/302f8db0-6c6e-40de-8dd2-dd1508fe9a6f)

**Comment by ronghanghu** [comment]
Hi @MuhammadTayab, currently SAM 2 is not supported on Google TPUs. This is primarily because at this moment, Google TPUs provide only very limited support for PyTorch and don't have all the functionalities and operations used in SAM 2. It's recommended to use GPUs for SAM 2.

**Comment by ronghanghu** [comment]
Hi @MR-HYS Please install SAM 2 first (see https://github.com/facebookresearch/segment-anything-2/issues/233#issuecomment-2294869403)

**Comment by MuhammadTayab** [comment]
Thanks for your reply @ronghanghu.
Can you suggest me a GPU for 2 frames per second processing speed on a standard core i5 ubuntu computer?
I want to use it for captured images but it's processing time recently is about 6 - 7 seconds which is not appropriate.
will rtx 3060 work for this ?
