### ISSUE TITLE
cannot import name '_C' from 'sam2'

### ISSUE THREAD

**Issue by chenbinghui1** [facebookresearch/segment-anything-2#25]
When I use SAM2 on image segmentation, it is ok. But for video segmentation, the above error occurs. How could i fix this bug?
pytorch 2.3.1
cuda: 12.1

**Comment by JBYan** [comment]
I encountered the same issue; the "libc10.so" library could not be found for Python. I resolved this by adjusting the environment variables.

`export LD_LIBRARY_PATH=/path/to/libc10.so:$LD_LIBRARY_PATH`

**Comment by 5d6d0011** [comment]
You can copy '_c.pyd' to sam2, and then 'from sam2 import _C'

**Comment by ddshan** [comment]
I had the same issue.
Solved by building extension: `python setup.py build_ext --inplace`

**Comment by Dutra-Apex** [comment]
I believe it's the same issue as #22 , which you can solve by running `python setup.py build_ext --inplace` or by downgrading pytorch to 2.1.0

**Comment by pinguo-huxiaohe** [comment]
> I had the same issue. Solved by building extension: `python setup.py build_ext --inplace`

Thanks, solved my problem
