### ISSUE TITLE
MissingConfigException, what's the cfg name for sam2_hiera_base_plus.pt?

### ISSUE THREAD

**Issue by yichuan1998** [facebookresearch/segment-anything-2#254]
It will be nice if there is a table which lists the cfg names for all .pt files
![image](https://github.com/user-attachments/assets/d92f5d10-8e7f-4f51-b6c2-ee0409383a2f)

**Comment by Antuainy** [comment]
[admin_depext,+11+RAIMUNDO+-+NOVO.pdf](https://github.com/user-attachments/files/16729499/admin_depext.%2B11%2BRAIMUNDO%2B-%2BNOVO.pdf)

**Comment by Pelirrojo** [comment]
Hi,

The file is in the repo: [sam2_hiera_b+.yaml](https://github.com/facebookresearch/segment-anything-2/blob/main/sam2_configs/sam2_hiera_b%2B.yaml)

so: value **sam2_configs/sam2_hiera_b+.yaml**

```python

# TINY
#sam2_checkpoint = "../checkpoints/sam2_hiera_tiny.pt"
#model_cfg = "sam2_hiera_t.yaml"

# BASE PLUS
#sam2_checkpoint = "../checkpoints/sam2_hiera_base_plus.pt"
#model_cfg = "sam2_configs/sam2_hiera_b+.yaml"

# SMALL
sam2_checkpoint = "../checkpoints/sam2_hiera_small.pt"
model_cfg = "sam2_hiera_s.yaml"

# LARGE
#sam2_checkpoint = "../checkpoints/sam2_hiera_large.pt"
#model_cfg = "sam2_hiera_l.yaml"

```

**Comment by yichuan1998** [comment]
> Hi,
> 
> The file is in the repo: [sam2_hiera_b+.yaml](https://github.com/facebookresearch/segment-anything-2/blob/main/sam2_configs/sam2_hiera_b%2B.yaml)
> 
> so: value **sam2_configs/sam2_hiera_b+.yaml**
> 
> ```python
> # TINY
> #sam2_checkpoint = "../checkpoints/sam2_hiera_tiny.pt"
> #model_cfg = "sam2_hiera_t.yaml"
> 
> # BASE PLUS
> #sam2_checkpoint = "../checkpoints/sam2_hiera_base_plus.pt"
> #model_cfg = "sam2_hiera_b+.yaml"
> 
> # SMALL
> sam2_checkpoint = "../checkpoints/sam2_hiera_small.pt"
> model_cfg = "sam2_hiera_s.yaml"
> 
> # LARGE
> #sam2_checkpoint = "../checkpoints/sam2_hiera_large.pt"
> #model_cfg = "sam2_hiera_l.yaml"
> ```
thanks!
