### ISSUE TITLE
MissingConfigException: Cannot find primary config

### ISSUE THREAD

**Issue by SkalskiP** [facebookresearch/segment-anything-2#26]
When installing SAM2 like this `pip install -q 'git+https://github.com/facebookresearch/segment-anything-2.git'` (I know it's different than instructions provided in `README.md`) I'm getting `MissingConfigException: Cannot find primary config 'sam2_hiera_l.yaml'. Check that it's in your config search path.` when I load the model.

```
import torch
from sam2.build_sam import build_sam2
from sam2.sam2_image_predictor import SAM2ImagePredictor

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
CHECKPOINT = f"{HOME}/checkpoints/sam2_hiera_large.pt"
CONFIG = "sam2_hiera_l.yaml"
```

```
MissingConfigException                    Traceback (most recent call last)
[<ipython-input-11-1cf64129701c>](https://localhost:8080/#) in <cell line: 9>()
      7 CONFIG = "sam2_hiera_l.yaml"
      8 
----> 9 sam2_model = build_sam2(CONFIG, CHECKPOINT, device=DEVICE)

11 frames
[/usr/local/lib/python3.10/dist-packages/hydra/_internal/defaults_list.py](https://localhost:8080/#) in config_not_found_error(repo, tree)
    797     msg += "\nConfig search path:" + f"\n{lines}"
    798 
--> 799     raise MissingConfigException(
    800         missing_cfg_file=element.get_config_path(),
    801         message=msg,

MissingConfigException: Cannot find primary config 'sam2_hiera_l.yaml'. Check that it's in your config search path.

Config search path:
	provider=hydra, path=pkg://hydra.conf
	provider=main, path=pkg://sam2_configs
	provider=schema, path=structured://
```

Where should I put the config so it can be discovered by SAM2?

**Comment by 0xIbra** [comment]
At the same level as your script, you must have the `sam2_configs` folder containing the yaml config files.

**Comment by ShuoShenDe** [comment]
I solved this problem. It is because your python environment not included your current path, which include sam2_configs
So you just add PYTHONPATH:
`export PYTHONPATH=$PYTHONPATH:$(pwd)`

**Comment by katelgote** [comment]
I solved the issue by adding the project directory to sys path:- 
sys.path.append("/your/base/path/segment-anything-2-main")

Then:-
from sam2.build_sam import build_sam2
from sam2.automatic_mask_generator import SAM2AutomaticMaskGenerator

sam2_checkpoint = "/path/to/checkpoint/sam2_hiera_large.pt"
model_cfg = "sam2_hiera_l.yaml" #Here keep only the name of the file.
sam2 = build_sam2(model_cfg, sam2_checkpoint, device ='cuda:2', apply_postprocessing=False)
mask_generator = SAM2AutomaticMaskGenerator(sam2)

**Comment by YasserElj** [comment]
you can find the package directory by
`pip show SAM-2`
go to the packages path you get
`path to packages /site-packages`

copy the your  `.yaml `config file into `sam2_configs` under the `/site-packages/`

then us this code :
```
sam2_checkpoint = "checkpoints/sam2_hiera_large.pt"
model_cfg = "sam2_hiera_l.yaml"

sam2_model = build_sam2(model_cfg, sam2_checkpoint, device="cuda")

predictor = SAM2ImagePredictor(sam2_model)
```

_Originally posted by @YasserElj in https://github.com/facebookresearch/segment-anything-2/issues/81#issuecomment-2262817396_

**Comment by ronghanghu** [comment]
Hi, we have added [`INSTALL.md`](https://github.com/facebookresearch/segment-anything-2/blob/main/INSTALL.md) as an installation FAQ.

Regarding this error:

This is usually because you haven't run the `pip install -e .` step above, so `sam2_configs` isn't in your Python's `sys.path`. (Please run this installation step first). In case it still fails after the installation step, you may try manually adding the root of this repo to `PYTHONPATH` via
```bash
export SAM2_REPO_ROOT=/path/to/segment-anything  # path to this repo
export PYTHONPATH="${SAM2_REPO_ROOT}:${PYTHONPATH}"
```
to manually add `sam2_configs` into your Python's `sys.path`.

**Comment by PhucNDA** [comment]
Here are my steps:

Delete the old segment-anything-v2 work folder. Make sure hydra pointing to new sam2 workspace
Copy `sam2.1_hiera_l.yaml` or whatever configs you want file to `./sam2/sam2`

Issue solved!

**Comment by pachu-um** [comment]
none of this working... i am tired really 
i am running in colab any change when we use colab ?

**Comment by pachu-um** [comment]
i had same issue
i amusing colab and i have  cloned the repo in /content/segment-anything-2
i copied the yaml file in  /content/segment-anything-2/sam2
and it worked

**Comment by UrFavouriteB0i** [comment]
> At the same level as your script, you must have the `sam2_configs` folder containing the yaml config files.

hey i know it's a bit late, in my current case i build docker image that utilize the sam2.1, does your comment refer to i should've use virtual env in my docker image so that it will store the sam2.1/config at the same level as my script? because currently i directly pip install in my global docker `usr/local/lib....`

**Comment by guiyuliu** [comment]
because hydra init like this: 
 hydra.initialize_config_module('sam2', version_base='1.2')
The first param 'sam2' is the module name, that means the module is  sam2/sam2 (it has __init__.py) , your config file must exist in this folder. not in the subfile  like  sam2/sam2/config/
