### ISSUE TITLE
Feature Request: Enable Support for non CUDA Devices.

### ISSUE THREAD

**Issue by jonhurlock** [facebookresearch/segment-anything-2#34]
Im currently using M3 Silicon on a MacBook Pro. Currently the code only support CUDA enabled devices. Is there any plan to start to support Metal Performance Shaders (MPS), rather than just CUDA?

**Comment by mashb1t** [comment]
+1, cross reference see https://github.com/lllyasviel/Fooocus/discussions/3406.
Fooocus is using SAM 1.0, support for AMD, MPS and CPU would highly be appreciated!

**Comment by jack-gits** [comment]
It would be great!! Specially for MacBooks and non GPU laptops

**Comment by vogel2** [comment]
We need mps support!

**Comment by vivasvan-patel-ev** [comment]
Support of Mac chips is highly required

**Comment by sangwf** [comment]
yes. I need it too.

**Comment by daikiad** [comment]
I have made changes to enable compatibility with Apple's MPS. 
https://github.com/facebookresearch/segment-anything-2/pull/123
Although it's not yet merged, you can check the changes in my forked repository (https://github.com/daikiad/segment-anything-2/tree/add-mps-support). I have tested the SAM2 sample notebook, and it runs mostly successfully. hope this will help

**Comment by ronghanghu** [comment]
Hi @emi-dm, we have added support for CPU and MPS devices in https://github.com/facebookresearch/segment-anything-2/pull/192, and updated the notebook examples. You can pull the latest code from this repository to try it out. Thanks!
