### ISSUE TITLE
can't install getting "Please make sure you have the correct access rights"

### ISSUE THREAD

**Issue by bdv29** [facebookresearch/segment-anything-2#38]
trying to install this on local computer 

getting :

Cloning into 'segment-anything-2'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.      
                                                   
Please make sure you have the correct access rights
and the repository exists.         

was there like some sort of acess key im suppose to get?

**Comment by emi-dm** [comment]
Add a ssh key to your github

**Comment by robertknight** [comment]
Alternatively you can clone the repository via HTTP:

```
git clone https://github.com/facebookresearch/segment-anything-2.git
```

I would suggest that the README should be updated to use HTTP for the checkout instructions, since it will work for more people in more places.

**Comment by bdv29** [comment]
> Alternatively you can clone the repository via HTTP:
> 
> ```
> git clone https://github.com/facebookresearch/segment-anything-2.git
> ```
> 
> I would suggest that the README should be updated to use HTTP for the checkout instructions, since it will work for more people in more places.

this work, thank you.

**Comment by robertknight** [comment]
This issue was fixed in https://github.com/facebookresearch/segment-anything-2/pull/64 and can be closed.

**Comment by ronghanghu** [comment]
> Alternatively you can clone the repository via HTTP:
> 
> ```
> git clone https://github.com/facebookresearch/segment-anything-2.git
> ```
> 
> I would suggest that the README should be updated to use HTTP for the checkout instructions, since it will work for more people in more places.

Thanks! We have updated the repo links to HTTPS and it should work now.
