### ISSUE TITLE
Google Colab example

### ISSUE THREAD

**Issue by ZlodeiBaal** [facebookresearch/segment-anything-2#40]
Not an issue. If someone needs it, I build a working Colab with the model - https://colab.research.google.com/drive/1Un09HITLLM-ljkG1Ehn9cJjdwk8FVI_1?usp=sharing

Working end-to-end.

**Comment by amrrs** [comment]
Thank you @ZlodeiBaal

**Comment by someshfengde** [comment]
my notebook link: https://www.kaggle.com/somesh88/sam-2-large-demo

**Comment by haithamkhedr** [comment]
Hi @ZlodeiBaal, we now support Colab for all our notebooks.
