### ISSUE TITLE
RuntimeError: No available kernel. Aborting execution.

### ISSUE THREAD

**Issue by Pizzawookiee** [facebookresearch/segment-anything-2#48]
My code:

import torch
import numpy as np
from sam2.build_sam import build_sam2
from sam2.automatic_mask_generator import SAM2AutomaticMaskGenerator
from PIL import Image

torch.autocast(device_type="cuda", dtype=torch.bfloat16).__enter__()

sam2_checkpoint = "checkpoints/sam2_hiera_tiny.pt"
model_cfg = "sam2_hiera_t.yaml"

sam2 = build_sam2(model_cfg, sam2_checkpoint, device ='cuda', apply_postprocessing=False)

mask_generator = SAM2AutomaticMaskGenerator(sam2)

image = Image.open('test.jpg')
image = np.array(image.convert("RGB"))

masks = mask_generator.generate(image)

print(len(masks))

The error ends in this:
segment-anything-2\sam2\modeling\sam\transformer.py", line 255, in forward
    out = F.scaled_dot_product_attention(q, k, v, dropout_p=dropout_p)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: No available kernel. Aborting execution.

**Comment by Jiaheliu137** [comment]
I encountered the same issue in the 27th code block of `image_predictor_example.ipynb`. My CUDA version is 12.4, and the PyTorch version is '2.4.0+cu124'.

**Comment by Pizzawookiee** [comment]
I have PyTorch version 2.3.1+cu121

**Comment by DronHazra** [comment]
Also have this issue, pytorch version `py3.11_cuda12.1_cudnn8.9.2_0`

**Comment by lclichen** [comment]
The same issue, with py3.10+PyTorch 2.4.0+cu121

**Comment by lclichen** [comment]
> The same issue, with py3.10+PyTorch 2.4.0+cu121

I solved this issue by adding some lines after [L22](https://github.com/facebookresearch/segment-anything-2/blob/86827e2fbae8a293f61d51caa70a4b0602c04454/sam2/modeling/sam/transformer.py#L22) in `sam2\modeling\sam\transformer.py`

```python
USE_FLASH_ATTN = False
MATH_KERNEL_ON = True
OLD_GPU = True
```

**Comment by Pizzawookiee** [comment]
Thanks, works for me

**Comment by Pizzawookiee** [comment]
> > The same issue, with py3.10+PyTorch 2.4.0+cu121
> 
> I solved this issue by adding some lines after [L22](https://github.com/facebookresearch/segment-anything-2/blob/86827e2fbae8a293f61d51caa70a4b0602c04454/sam2/modeling/sam/transformer.py#L22) in `sam2\modeling\sam\transformer.py`
> 
> ```python
> USE_FLASH_ATTN = False
> MATH_KERNEL_ON = True
> OLD_GPU = True
> ```

Thanks, works for me

**Comment by biaggii** [comment]
> > The same issue, with py3.10+PyTorch 2.4.0+cu121
> 
> I solved this issue by adding some lines after [L22](https://github.com/facebookresearch/segment-anything-2/blob/86827e2fbae8a293f61d51caa70a4b0602c04454/sam2/modeling/sam/transformer.py#L22) in `sam2\modeling\sam\transformer.py`
> 
> ```python
> USE_FLASH_ATTN = False
> MATH_KERNEL_ON = True
> OLD_GPU = True
> ```

Thanks, works for me too

**Comment by mrc736** [comment]
> > The same issue, with py3.10+PyTorch 2.4.0+cu121
> 
> I solved this issue by adding some lines after [L22](https://github.com/facebookresearch/segment-anything-2/blob/86827e2fbae8a293f61d51caa70a4b0602c04454/sam2/modeling/sam/transformer.py#L22) in `sam2\modeling\sam\transformer.py`
> 
> ```python
> USE_FLASH_ATTN = False
> MATH_KERNEL_ON = True
> OLD_GPU = True
> ```

Thansk, it works for me. what is the reason?

**Comment by happybear1015** [comment]
good，确实解决了我的问题，在执行预测的时候。

**Comment by ronghanghu** [comment]
Hi, we have added [`INSTALL.md`](https://github.com/facebookresearch/segment-anything-2/blob/main/INSTALL.md) as an installation FAQ.

Regarding this error:

This is probably because your machine doesn't have a GPU or a compatible PyTorch version for Flash Attention (see also https://discuss.pytorch.org/t/using-f-scaled-dot-product-attention-gives-the-error-runtimeerror-no-available-kernel-aborting-execution/180900 for a discussion in PyTorch forum). You may be able to resolve this error by replacing the line
```python
OLD_GPU, USE_FLASH_ATTN, MATH_KERNEL_ON = get_sdpa_settings()
```
in [`sam2/modeling/sam/transformer.py`](sam2/modeling/sam/transformer.py) with
```python
OLD_GPU, USE_FLASH_ATTN, MATH_KERNEL_ON = True, True, True
```
to relax the attention kernel setting and use other kernels than Flash Attention.

**Comment by YMKiii** [comment]
import torch

**Comment by 48hour** [comment]
> > The same issue, with py3.10+PyTorch 2.4.0+cu121
> 
> I solved this issue by adding some lines after [L22](https://github.com/facebookresearch/segment-anything-2/blob/86827e2fbae8a293f61d51caa70a4b0602c04454/sam2/modeling/sam/transformer.py#L22) in `sam2\modeling\sam\transformer.py`
> 
> ```python
> USE_FLASH_ATTN = False
> MATH_KERNEL_ON = True
> OLD_GPU = True
> ```

Thanks for solve this issue.

**Comment by SRDdev** [comment]
Hey,
Thanks for your help this solved my issue as well, would like to go deeper and understand what is actually causing the issue ?

> > The same issue, with py3.10+PyTorch 2.4.0+cu121
> 
> I solved this issue by adding some lines after [L22](https://github.com/facebookresearch/segment-anything-2/blob/86827e2fbae8a293f61d51caa70a4b0602c04454/sam2/modeling/sam/transformer.py#L22) in `sam2\modeling\sam\transformer.py`
> 
> USE_FLASH_ATTN = False
> MATH_KERNEL_ON = True
> OLD_GPU = True
