### ISSUE TITLE
ERROR: Could not build wheels for SAM-2, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by DoiryCool** [facebookresearch/segment-anything-2#50]
When i run pip install -e ".[demo]",it shows:  
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for SAM-2
Failed to build SAM-2
ERROR: Could not build wheels for SAM-2, which is required to install pyproject.toml-based projects

**Comment by patermars** [comment]
Kindly look into issue #18  and #21. You will find your solution.

**Comment by DoiryCool** [comment]
> Kindly look into issue #18 and #21. You will find your solution.

Solved By Upgrade CUDA to 12.1，THX
