### ISSUE TITLE
My example CONFIG must be a relative path; specifying an absolute path will result in an error: MissingConfigException: Cannot find primary config.

### ISSUE THREAD

**Issue by ArachisTong** [facebookresearch/segment-anything-2#58]
My example CONFIG must be a relative path; specifying an absolute path will result in an error: MissingConfigException: Cannot find primary config.

this is my code：
```
sam2_checkpoint = "/path/sam2_hiera_large.pt"
# hydra的bug,只能使用相对路径
# model_cfg = "../sam2_configs/sam2_hiera_l.yaml"
model_cfg = "/data1/segment-anything-2/sam2_configs/sam2_hiera_l.yaml"

sam2_model = build_sam2(model_cfg, sam2_checkpoint, device="cuda")

predictor = SAM2ImagePredictor(sam2_model)
```

File /opt/conda/envs/sam/lib/python3.10/site-packages/hydra/_internal/defaults_list.py:799, in config_not_found_error(repo, tree)
    796 lines = "\n".join(descs)
    797 msg += "\nConfig search path:" + f"\n{lines}"
--> 799 raise MissingConfigException(
    800     missing_cfg_file=element.get_config_path(),
    801     message=msg,
    802     options=options,
    803 )

MissingConfigException: Cannot find primary config 'data1/segment-anything-2/sam2_configs/sam2_hiera_l.yaml'. Check that it's in your config search path.

Config search path:
	provider=hydra, path=pkg://hydra.conf
	provider=main, path=pkg://sam2_configs
	provider=schema, path=structured://

_Originally posted by @ArachisTong in https://github.com/facebookresearch/segment-anything-2/issues/26#issuecomment-2259869807_

**Comment by dnnxl** [comment]
Hi! I also use the following command to install SAM 2 `pip` install -q 'git+https://github.com/facebookresearch/segment-anything-2.git'` but still getting the error when I'm using Google Colab, can you explain how you solve it? I tried relative and absolute path, none works

**Comment by omry** [comment]
This looks like the same underlying issue tracked in #758.

`build_sam2()` currently passes its `config_file` argument directly to Hydra as `compose(config_name=...)`. In Hydra, `config_name` is resolved from the configured search path; it is not an arbitrary absolute filesystem path.

I added more context and a user-side workaround here:

https://github.com/facebookresearch/sam2/issues/758#issuecomment-4764826366

The workaround keeps the two concepts separate:

- `config_dir`: where Hydra should search for configs
- `config_name`: the config name resolved inside that directory

That also allows the user config directory to contain additional subconfigs referenced from the user config's defaults list.
