### ISSUE TITLE
from sam2 import _C error

### ISSUE THREAD

**Issue by the-cat-crying** [facebookresearch/segment-anything-2#59]
...
mask_generator_2 = SAM2AutomaticMaskGenerator(
    model=sam2,
    points_per_side=64,
    points_per_batch=128,
    pred_iou_thresh=0.7,
    stability_score_thresh=0.92,
    stability_score_offset=0.7,
    crop_n_layers=1,
    box_nms_thresh=0.7,
    crop_n_points_downscale_factor=2,
    min_mask_region_area=25.0,
    use_m2m=True,
)

masks = mask_generator_2.generate(image)
...

  File "../segment/segment-anything-2/sam2/utils/misc.py", line 61, in get_connected_components
    from sam2 import _C
ImportError: cannot import name '_C' from 'sam2' (../segment/segment-anything-2/sam2/__init__.py)

**Comment by the-cat-crying** [comment]
I tested the same image and found that the SAM1 version works better, is there a requirement for the GPU? My GPU Ampere < (8.0)

**Comment by yinnhao** [comment]
Confirm if running `pip install -e .` was executed correctly, or use `python setup.py build_ext` to compile _C.so only. If you prefer to use the local code instead of installing the library, then use `python setup.py build_ext --inplace`, and you will get _C.so in 'segment-anything-2/sam2/'.

**Comment by patermars** [comment]
> Confirm if running `pip install -e .` was executed correctly, or use `python setup.py build_ext` to compile _C.so only. If you prefer to use the local code instead of installing the library, then use `python setup.py build_ext --inplace`, and you will get _C.so in 'segment-anything-2/sam2/'.


I tried that but i couldn't get it to work when i try it. It gives me this error:

```
running build_ext
/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py:499: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py:418: UserWarning: The detected CUDA version (12.2) has a minor version mismatch with the version that was used to compile PyTorch (12.1). Most likely this shouldn't be a problem.
  warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py:428: UserWarning: There are no x86_64-linux-gnu-g++ version bounds defined for CUDA version 12.2
  warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
building 'sam2._C' extension
/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py:1967: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
/usr/local/cuda/bin/nvcc -I/usr/local/lib/python3.10/dist-packages/torch/include -I/usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.10/dist-packages/torch/include/TH -I/usr/local/lib/python3.10/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.10 -c sam2/csrc/connected_components.cu -o build/temp.linux-x86_64-cpython-310/sam2/csrc/connected_components.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 -std=c++17
cc1plus: fatal error: sam2/csrc/connected_components.cu: No such file or directory
compilation terminated.
error: command '/usr/local/cuda/bin/nvcc' failed with exit code 1
```

It tells me that couldn't find ninja? set up os.environ['TORCH_CUDA_ARCH_LIST']

Getting too confusing for me. I checked issue #22 and #14 but nothing working for me. Do you have any idea why and how to get by it?

**Comment by patermars** [comment]
Nvm, i fixed it.

It needed ninja to be installed 
```
!pip install ninja
```
and then with some relative address fix in setup.py, everything worked.

**Comment by the-cat-crying** [comment]
thanks!

**Comment by ronghanghu** [comment]
Hi, we have added [`INSTALL.md`](https://github.com/facebookresearch/segment-anything-2/blob/main/INSTALL.md) as an installation FAQ.

Regarding this error:

This is usually because you haven't run the `pip install -e ".[demo]"` step above or the installation failed. Please install SAM 2 first, and see the other issues if your installation fails. (You may also try `python setup.py build_ext --inplace` in the repo root as others suggested in https://github.com/facebookresearch/segment-anything-2/issues/77)
