### ISSUE TITLE
How to run the startup program

### ISSUE THREAD

**Issue by ldqrecord** [facebookresearch/segment-anything-2#70]
automatic_mask_generator_example.ipynb 。Is it this file? How to run it?

**Comment by ronghanghu** [comment]
Hi, you may start with one of the notebooks below:

- For static image segmentation with prompts: https://github.com/facebookresearch/segment-anything-2/blob/main/notebooks/image_predictor_example.ipynb

- For automatic mask generation in images: https://github.com/facebookresearch/segment-anything-2/blob/main/notebooks/automatic_mask_generator_example.ipynb

- For video segmentation with prompts: https://github.com/facebookresearch/segment-anything-2/blob/main/notebooks/video_predictor_example.ipynb
