### ISSUE TITLE
Does SAM2 support CPU?

### ISSUE THREAD

**Issue by asmith26** [facebookresearch/segment-anything-2#71]
Hi, just wondering does this support CPU?

In the [installatation](https://github.com/facebookresearch/segment-anything-2?tab=readme-ov-file#installation) notes it says use a GPU, but just thought I'd ask if there is any reason why it won't work on CPU  (of course I appreciate performance will be much slower).

Thanks!

**Comment by amirmohammadnsh** [comment]
I think this fork of SAM2 by @SauravMaheshkar is useful for you: https://github.com/SauravMaheshkar/samv2

**Comment by SauravMaheshkar** [comment]
@amirmohammadnsh thanks for tagging. 

@asmith26 so the codebase works perfectly fine on CPU (you can play around with it here https://huggingface.co/spaces/lightly-ai/SAMv2-Mask-Generator) it's just that you won't be able to install the python package since while downloading it requires a custom CUDA kernel as mentioned here:

https://github.com/facebookresearch/segment-anything-2/blob/86827e2fbae8a293f61d51caa70a4b0602c04454/setup.py#L70-L71

**Comment by asmith26** [comment]
Many thanks @amirmohammadnsh  @SauravMaheshkar for your help/time/info, will look into samv2!

**Comment by emi-dm** [comment]
What is necessary for run the original implementation of SAM2 in only CPU device?

**Comment by emi-dm** [comment]
@SauravMaheshkar what you exactly do to port It to only CPU device ?

**Comment by SauravMaheshkar** [comment]
> @amirmohammadnsh thanks for tagging.
> 
> @asmith26 so the codebase works perfectly fine on CPU (you can play around with it here https://huggingface.co/spaces/lightly-ai/SAMv2-Mask-Generator) it's just that you won't be able to install the python package since while downloading it requires a custom CUDA kernel as mentioned here:
> 
> https://github.com/facebookresearch/segment-anything-2/blob/86827e2fbae8a293f61d51caa70a4b0602c04454/setup.py#L70-L71

@emi-dm as mentioned above. GPU is only needed to install the package since it uses a custom CUDA kernel. It can works fine on CPU device (https://huggingface.co/spaces/lightly-ai/SAMv2-Mask-Generator)

**Comment by emi-dm** [comment]
@SauravMaheshkar This is the case, the device on which I want to install the package does not have a GPU.

**Comment by ASBJ021** [comment]
> > @amirmohammadnsh thanks for tagging.
> > @asmith26 so the codebase works perfectly fine on CPU (you can play around with it here https://huggingface.co/spaces/lightly-ai/SAMv2-Mask-Generator) it's just that you won't be able to install the python package since while downloading it requires a custom CUDA kernel as mentioned here:
> > https://github.com/facebookresearch/segment-anything-2/blob/86827e2fbae8a293f61d51caa70a4b0602c04454/setup.py#L70-L71
> 
> @emi-dm as mentioned above. GPU is only needed to install the package since it uses a custom CUDA kernel. It can works fine on CPU device (https://huggingface.co/spaces/lightly-ai/SAMv2-Mask-Generator)

Hi,
I am trying to run SAM2 on mac m2, which doesn't have GPU support for CUDA. Could you guide me to run this using only CPU. I tried to run your code and I can't see any output or plots( even though it runs without any error).

Thanks in Advance,
Akash

**Comment by SauravMaheshkar** [comment]
Hey @ASBJ021 I've added a [notebook](https://github.com/SauravMaheshkar/samv2/blob/main/examples/notebooks/samv2_prompted_segmentation_with_wandb_tables.ipynb) to my fork that shows how you can use SAM2 in various prompted scenarios. The latest changes also contain a utility function that helps visualize the outputs. In some time, I'll also add notebooks + scripts for automatic mask generation and interactive video segmentation. 

You can directly access that notebook in colab here <a href="https://colab.research.google.com/github/SauravMaheshkar/samv2/blob/main/examples/notebooks/samv2_prompted_segmentation_with_wandb_tables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Feel free to open issues over on the fork, if you want help with something else.

**Comment by ASBJ021** [comment]
> Hey @ASBJ021 I've added a [notebook](https://github.com/SauravMaheshkar/samv2/blob/main/examples/notebooks/samv2_prompted_segmentation_with_wandb_tables.ipynb) to my fork that shows how you can use SAM2 in various prompted scenarios. The latest changes also contain a utility function that helps visualize the outputs. In some time, I'll also add notebooks + scripts for automatic mask generation and interactive video segmentation.
> 
> You can directly access that notebook in colab here [![Open In Colab](https://camo.githubusercontent.com/f5e0d0538a9c2972b5d413e0ace04cecd8efd828d133133933dfffec282a4e1b/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/SauravMaheshkar/samv2/blob/main/examples/notebooks/samv2_prompted_segmentation_with_wandb_tables.ipynb)
> 
> Feel free to open issues over on the fork, if you want help with something else.

Hi @SauravMaheshkar ,

Thanks for the reply. It helped me a lot and it worked great. I was working on video bg removal program and wanted to use SAM2 to crate masks.

Thanks a lot,
Akash
