### ISSUE TITLE
fpn `nearest` interpolate 

### ISSUE THREAD

**Issue by bhack** [facebookresearch/segment-anything-2#74]
I've seen that all the configuration are going to use `nearest` in the `fpn` interpolation mode. 
Are we not affected by https://github.com/pytorch/pytorch/issues/34808 ?

**Comment by ronghanghu** [comment]
Hi @bhack, this `nearest` interpolation follows the standard FPN implementation as in Detectron2 (https://github.com/facebookresearch/detectron2/blob/31bebdea147c96f8a00a0d55931858bf727ae370/detectron2/modeling/backbone/fpn.py#L153) and wouldn't be affected by https://github.com/pytorch/pytorch/issues/34808 in this case. See also more discussions on the align_corner option in https://github.com/pytorch/pytorch/issues/34808#issuecomment-880882124.
