### ISSUE TITLE
Config files are missing --> hydra.errors.MissingConfigException:Cannot find primary config 'sam2_hiera_l.yaml' 

### ISSUE THREAD

**Issue by delvingdeep** [facebookresearch/segment-anything-2#81]
While loading sam2 model in predictor, got an error for loading config file:
```bash
"hydra.errors.MissingConfigException: Cannot find primary config 'sam2_hiera_l.yaml'. Check that it's in your config search path.

Config search path:
	provider=hydra, path=pkg://hydra.conf
	provider=main, path=pkg://sam2_configs
	provider=schema, path=structured://
```

sam2 config files at `/sam2_configs` are missing from hydra config search path. 

It would be great if they are added at package level and hence no `hydra.errors.MissingConfigException`

**Comment by liweiyangv** [comment]
copy the sam2_configs folder under the root project path

**Comment by CoderZhangYx** [comment]
modify [here](https://github.com/facebookresearch/segment-anything-2/blob/main/sam2/__init__.py#L9).
add relative path to the first param.

**Comment by Zora333** [comment]
I encountered the same problem. I use the code below to solve hydra.errors.MissingConfigException, while a new error occurs: `ConfigAttributeError: Key 'endswith' is not in struct` . 
It seems that the config file cannot be parsed properly.
Can anyone please help?
```
from hydra import initialize, compose
from sam2.build_sam import build_sam2

config_dir="./sam2_configs"
model_cfg = "sam2_hiera_l.yaml"
sam2_checkpoint = "./checkpoints/sam2_hiera_large.pt"

with initialize(config_path=config_dir):
    cfg = compose(config_name=model_cfg)
    sam2_model = build_sam2(cfg, sam2_checkpoint, device="cuda")

predictor = SAM2ImagePredictor(sam2_model)
```

**Comment by YasserElj** [comment]
you can do
`pip show SAM-2`
go to the packages path you get
`path to packages /site-packages`

copy the `.yaml `config file into `sam2_configs` under the `/site-packages/`

then us this code :
```
sam2_checkpoint = "checkpoints/sam2_hiera_large.pt"
model_cfg = "sam2_hiera_l.yaml"

sam2_model = build_sam2(model_cfg, sam2_checkpoint, device="cuda")

predictor = SAM2ImagePredictor(sam2_model)
```

**Comment by catalys1** [comment]
You can fix it by reconfiguring the Hydra search path. This worked for me:
```python
import hydra
from sam2.build_sam import build_sam2

# hydra is initialized on import of sam2, which sets the search path which can't be modified
# so we need to clear the hydra instance
hydra.core.global_hydra.GlobalHydra.instance().clear()
# reinit hydra with a new search path for configs
hydra.initialize_config_module('<path-to-sam2_configs>', version_base='1.2')

# this should work now
model = build_sam2('<config-name>', '<checkpoint-path>')
```

**Comment by delvingdeep** [comment]
I was able to resolve this issue by building C extensions and placing the complied module in the source directory. 
```
python setup.py build_ext --inplace
```

**Comment by lxin98** [comment]
> copy the sam2_configs folder under the root project path
works for me,thanks

**Comment by royvelich** [comment]
I suggested a fix if anyone is interested:
https://github.com/facebookresearch/segment-anything-2/pull/188

**Comment by AmirulOm** [comment]
I fix by placing `__init__.py` in your root project (assuming that you are storing the `.yaml` file in the root project too). To be specific, i created a folder `sam2_configs` too. Here is the folder structure

```
- __init__.py
- sam2_configs/
   - __init__.py
   - sam2_hiera_l.yaml

**Comment by matthias-tschoepe** [comment]
I also got this error, although I tried all before mentioned solutions, but nothing worked for me. So, I had a look at the hydra implementation and in the docu of the compose function they mention the following:
```
def compose(
    config_name: Optional[str] = None,
    overrides: Optional[List[str]] = None,
    return_hydra_config: bool = False,
    strict: Optional[bool] = None,
) -> DictConfig:
    """
    :param config_name: the name of the config
           (usually the file name without the .yaml extension)
    :param overrides: list of overrides for config file
    :param return_hydra_config: True to return the hydra config node in the result
    :param strict: DEPRECATED. If false, returned config has struct mode disabled.
    :return: the composed config
    """
```
So, I tried 
`sam2_model = build_sam2("sam2_hiera_s", sam2_checkpoint, device=device, apply_postprocessing=False)`
instead of
`sam2_model = build_sam2("/PATH_TO_CONFIG/sam2_hiera_s.yaml", sam2_checkpoint, device=device, apply_postprocessing=False)`
and everything worked fine. I'm not sure if it is only me, but maybe it helps someone.

**Comment by bulat15g** [comment]
just model_cfg = "sam2_hiera_l.yaml" without full path worked for me

**Comment by myendless1** [comment]
> I also got this error, although I tried all before mentioned solutions, but nothing worked for me. So, I had a look at the hydra implementation and in the docu of the compose function they mention the following:
> 
> ```
> def compose(
>     config_name: Optional[str] = None,
>     overrides: Optional[List[str]] = None,
>     return_hydra_config: bool = False,
>     strict: Optional[bool] = None,
> ) -> DictConfig:
>     """
>     :param config_name: the name of the config
>            (usually the file name without the .yaml extension)
>     :param overrides: list of overrides for config file
>     :param return_hydra_config: True to return the hydra config node in the result
>     :param strict: DEPRECATED. If false, returned config has struct mode disabled.
>     :return: the composed config
>     """
> ```
> 
> So, I tried `sam2_model = build_sam2("sam2_hiera_s", sam2_checkpoint, device=device, apply_postprocessing=False)` instead of `sam2_model = build_sam2("/PATH_TO_CONFIG/sam2_hiera_s.yaml", sam2_checkpoint, device=device, apply_postprocessing=False)` and everything worked fine. I'm not sure if it is only me, but maybe it helps someone.

relative path more than filename also works as the same, like "configs/sam2.1/sam2.1_hiera_t" insteal of "configs/sam2.1/sam2.1_hiera_t.yaml", thanks a lot.

**Comment by Zhengyu-Hu** [comment]
Use the relative path in `site-packages/sam2` instead of  your working directory.

**Comment by wahaha-debug** [comment]
Set sam2_checkpoint to ./checkpoints/sam2.1_hiera_small.pt instead of ../checkpoints/sam2.1_hiera_small.pt
Set model_cfg to ../sam2/configs/sam2.1/sam2.1_hiera_s.yaml instead of configs/sam2.1/sam2.1_hiera_s.yaml"

**Comment by FurkanGozukara** [comment]
i am giving direct path and failing https://github.com/facebookresearch/sam2/issues/544

it works in windows

**Comment by zobeirraisi** [comment]
The only thing that worked for me.
- First go to the folder of your samurai
- open a terminal there and find the path of current directory by `pwd`
- copy the path and replace in the following path to samurai

`export SAM2_REPO_ROOT=/path/to/samurai  # path to this repo

export PYTHONPATH="${SAM2_REPO_ROOT}:${PYTHONPATH}"`

- Then run them in the open terminal.

**Comment by imtheva** [comment]
I encountered the same issue with SAM2.1. However, I tried all the approaches mentioned here. I moved the entire config folder into the root SAM2 directory, and the code worked for me.

`configs/sam2.1/sam2.1_hiera_l.yaml`

**Comment by sago2693** [comment]
> Set sam2_checkpoint to ./checkpoints/sam2.1_hiera_small.pt instead of ../checkpoints/sam2.1_hiera_small.pt Set model_cfg to ../sam2/configs/sam2.1/sam2.1_hiera_s.yaml instead of configs/sam2.1/sam2.1_hiera_s.yaml"

Making it clear that sam2 is in the same folder as your project, it worked for me.

**Comment by StefanNa3Shape** [comment]
None of these tips helped me, but what did help were these adjustments to build_sam() where I read the YAML manually and pass it to the function.

```
from omegaconf import DictConfig
from hydra import compose
from hydra.utils import instantiate
from omegaconf import OmegaConf
import os
import torch

def build_sam2_(
    config_file,  # Can be a config name (str) or a DictConfig
    ckpt_path=None,
    device="cuda",
    mode="eval",
    hydra_overrides_extra=[],
    apply_postprocessing=True,
    **kwargs
):


    # Allow passing an actual config object
    if isinstance(config_file, DictConfig):
        cfg = config_file
    else:
        if apply_postprocessing:
            hydra_overrides_extra = hydra_overrides_extra.copy()
            hydra_overrides_extra += [
                "++model.sam_mask_decoder_extra_args.dynamic_multimask_via_stability=true",
                "++model.sam_mask_decoder_extra_args.dynamic_multimask_stability_delta=0.05",
                "++model.sam_mask_decoder_extra_args.dynamic_multimask_stability_thresh=0.98",
            ]

        cfg = compose(config_name=config_file, overrides=hydra_overrides_extra)

    OmegaConf.resolve(cfg)
    model = instantiate(cfg.model, _recursive_=True)

    if ckpt_path:
        checkpoint = torch.load(ckpt_path, map_location="cpu", weights_only=True)
        if "model" in checkpoint:
            model.load_state_dict(checkpoint["model"], strict=False)
        else:
            model.load_state_dict(checkpoint, strict=False)

    model.to(device)
    if mode == "train":
        model.train()
    else:
        model.eval()

    return model

# Load the YAML config manually from file
yaml_path = os.path.abspath("../external/sam2/sam2/configs/sam2.1/sam2.1_hiera_t.yaml")
cfg = OmegaConf.load(yaml_path)

# Set checkpoint path
sam2_checkpoint = "../data/leaf-seg/sam2.1_hiera_tiny.pt"
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

sam2_model = build_sam2_(cfg, sam2_checkpoint, device=DEVICE)
```

**Comment by developer0hye** [comment]
![Image](https://github.com/user-attachments/assets/26456cbb-2433-43da-81b9-8c41fe3db204)

- inferece.py
```python
import torch
from sam2.build_sam import build_sam2
from sam2.sam2_image_predictor import SAM2ImagePredictor
from hydra import initialize, compose
from hydra.core.global_hydra import GlobalHydra
from pathlib import Path

def main():
    model_cfg_path = Path("sam2/configs/sam2.1")
    model_cfg_file = "sam2.1_hiera_l"

    GlobalHydra.instance().clear()

    # 명시적 Hydra 초기화
    initialize(config_path=str(model_cfg_path), job_name="sam2_inference", version_base=None)

    sam2_model = build_sam2(model_cfg_file, device="cuda")

    predictor = SAM2ImagePredictor(sam2_model)

    GlobalHydra.instance().clear() 

if __name__ == "__main__":
    main()
```

I was able to load model with this code.

**Comment by hiyamdebary** [comment]
What worked for me is using the following path: 

`model_cfg = "configs/sam2.1/sam2.1_hiera_l.yaml" `

**Comment by Henry-city** [comment]
> What worked for me is using the following path:
> 
> `model_cfg = "configs/sam2.1/sam2.1_hiera_l.yaml" `

Thank you! This really works!And it requires "config" folder just in sam2 folder.

**Comment by SAgiKPJH** [comment]
When Hydra requires relative paths but you have absolute paths, change the working directory to the config location first, then use relative paths.

```python
import sam2
from sam2.build_sam import build_sam2
from sam2.automatic_mask_generator import SAM2AutomaticMaskGenerator
            
from hydra import initialize, compose
from hydra.core.global_hydra import GlobalHydra
GlobalHydra.instance().clear()

# Change working directory to config file location
# This allows Hydra to find config files using relative paths
original_cwd = os.getcwd()
os.chdir(base_path)  # Change to directory containing config files

# Initialize Hydra with relative path
initialize(config_path=".", job_name="sam2_inference", version_base=None)
config_file = "sam2.1_hiera_l.yaml"

# Load model
checkpoint_path = os.path.join(base_path, "sam2.1_hiera_large.pt")
model = build_sam2(config_file=config_file, ckpt_path=checkpoint_path, device="cuda")
```

**Comment by alessandriniluca** [comment]
May it be that if I am using hydra, this clashes with the hydra used by the project? As in my case it works fine if I open a terminal and load it manually, it crashes with this error if I run from an hydra script
