### ISSUE TITLE
Add Support to only CPU devices 

### ISSUE THREAD

**Issue by emi-dm** [facebookresearch/segment-anything-2#96]
Please, add Support to only CPU devices for video mode? Is there a solution?

**Comment by ronghanghu** [comment]
Currently there is a community implementation for CPU-only version in https://github.com/facebookresearch/segment-anything-2/issues/71#issuecomment-2261295494

**Comment by ronghanghu** [comment]
Hi @emi-dm, we have added support for CPU devices in https://github.com/facebookresearch/segment-anything-2/pull/192, and updated the notebook examples. You can pull the latest code from this repository to try it out. Thanks!
